### ISSUE TITLE
Save some state between runs

### ISSUE THREAD

**Issue by jmorris-frc2016** [Boomaa23/open-ds#13] opened 2022-06-14 19:28 UTC
Maybe I'm doing something wrong, but seems everytime I start the program I have to input my team number, is it possible to have it save that state?

**Comment by Boomaa23** [comment] 2022-06-15 01:59
Hi, that is the intended function of the program but I can add that feature when I get a chance.

**Comment by Boomaa23** [comment] 2022-06-16 04:18
@jmorris-frc2016 this feature should be implemented as of fde61e993c220e303c71a9c3b1da37bb4aaad7e1. Please let me know if you have any issues. Closing this issue as the feature has been implemented.

**Comment by jmorris-frc2016** [comment] 2022-06-22 20:34
Hey thanks for your quick responses on both of these! how do i get an updated jar file?

**Comment by Boomaa23** [comment] 2022-06-22 22:19
I'll publish another jar file next release, otherwise you can build from the source code.

**Comment by jmorris-frc2016** [comment] 2022-06-25 15:25
Hey Boomaa, I built and run the latest code but noticed it only persists between launches as long as the machine isnt powered off. (as in every cold boot requires you to type in your team number)

**Comment by Boomaa23** [comment] 2022-06-26 01:38
The persistent team number is written to your computer's temp directory, so this would indicate that your temp directory is being cleared on restart. I don't want to put the persistent file anywhere else since OpenDS doesn't really have a "home" directory. Regardless, this folder shouldn't be cleared by restart. Unfortunately I can't reproduce this error so I can't really help here.

**Comment by jmorris-frc2016** [comment] 2022-06-26 05:05
Thanks for getting back to me, I'm using a lightweight Linux distro (Q4OS)
so it could definitely be on my end. If I wanted to modify it to take a
couple things as command line parameters, is there a file that acts as an
entrypoint?

**Comment by NoahAndrews** [comment] 2022-06-26 05:09
> Regardless, this folder shouldn't be cleared by restart.

Why not, that's what I would expect. "Temporary" means that it won't last forever, so anything there should be safe to delete as long as it's not actively being used by a program.

**Comment by Boomaa23** [comment] 2022-06-26 05:26
Temporary generally doesn't mean that it'll be systematically reset, you can assume there will be some persistence there generally even if there is volatility in that. I think CLI parameters are a good idea, but I'd like to include more than just this if I was to have some CLI params. I will work on it.

**Comment by jmorris-frc2016** [comment] 2022-06-26 05:29
Yea, for command line arguments I'd love to have fms, usb, and team number.

**Comment by Boomaa23** [comment] 2022-06-26 07:59
Alright I've written something that should work, as of 9d75ddbb85b2106e2109d5ad2f8603cdbb998bb6. Use `--tpf [fileloc]` to specify the team number persist file (just a text file with a number in it) or `--team-num [number]` to directly set the team number. Let me know if you have issues.

**Comment by jmorris-frc2016** [comment] 2022-06-26 22:15
the command line arguments work great! im just using the --team-num version, but having both seems like a good idea, thanks Boomaa

**Closed** 2022-06-26 22:31 UTC
Labels: enhancement
